sonar.projectKey=Devops_CiCD_3TireProject
sonar.projectName=Devops_CiCD_3TireProject
sonar.organization=gmalo1998
sonar.sources=frontend,backend
sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarcloud.io