apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.mongodb.service.name }}"
  namespace: "{{ .Values.namespace }}"
spec:
  selector:
    app: "{{ .Values.mongodb.name }}"
  ports:
    - protocol: TCP
      port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.targetPort }}
  type: "{{ .Values.mongodb.service.type }}"