name: ChatApp CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pipeline Started
        run: echo "Build Started"

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Frontend Tests
        run: |
          cd frontend
          npm test

      - name: Backend Tests
        run: |
          cd backend
          npm test

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBETOKEN }}
        run: |
          npx sonar-scanner \
            -Dsonar.organization=gmalo1998 \
            -Dsonar.projectKey=Devops_CiCD_3TireProject \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "chatapp"
          path: "."
          format: "HTML"
          out: "reports"

      - name: Upload OWASP Report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-report
          path: reports

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Build Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/hellochat-frontend:latest ./frontend

      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/hellochat-frontend:latest

      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/hellochat-backend:latest ./backend

      - name: Push Backend Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/hellochat-backend:latest